name: init_val_generator
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - astropy=5.3.4
  - babel=2.11.0
  - black=24.3.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.11.0
  - docutils=0.18.1
  - expat=2.5.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - idna=3.4
  - imagesize=1.4.1
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mypy=1.8.0
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - pathspec=0.10.3
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - psutil=5.9.0
  - pyerfa=2.0.0
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pytest=7.4.0
  - python=3.12.2
  - python-dateutil=2.8.2
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=5.0.2
  - sphinx_rtd_theme=1.1.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.3.3
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
